import Head from "next/head";
import Navbar from "../components/UI/Navbar";
import ModalRender from "../components/Modal/ModalRender";
import { useDispatch, useSelector } from "react-redux";
import { uiActions } from "../store/uiSlice";
import { useState } from "react";
import { useEffect } from "react";
import Loading from "../components/UI/Loading";
import Footer from "../components/UI/Footer";
import i18n from "./config/i18n";
import styled from "styled-components";

export default function Home(props) {
	const dispatch = useDispatch();
	const showModalHandler = () => {
		dispatch(uiActions.showModal());
	};

	const [show, setShow] = useState(true);

	useEffect(() => {
		const timer = setTimeout(() => {
			setShow(false);
		}, 1000);

		return () => clearTimeout(timer);
	}, []);

	const lang = useSelector((state) => state.view.lang);

	useEffect(() => {
		i18n.changeLanguage(lang);
		console.log(lang);
	}, [lang]);

	return (
		<>
			<Head>
				<title>gnNews</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			{show ? (
				<Loading />
			) : (
				<>
					<Navbar onClick={showModalHandler} />
					<ModalRender onHide={showModalHandler} />
					<List>
						<ListItem>
							<Title>Zapraszam do aplikacji gnNews.</Title>
							<Description>
								Hej, jestem Oskar i mam przyjemność przedstawić wam moją
								aplikację gnNews. Jest to aplikacja, która pozwala na
								przeglądanie wiadomości z różnych źródeł. Aplikacja została
								napisana w React.js i Next.js. Źródła wiadomości to:
								NewsAPI.org.
							</Description>
							<Description>
								W Navbarze aplikacji możemy znaleźć selecta odpowiedzialnego za
								wybór, który pozwala na zmianę języka aplikacji. Modal Po
								kliknięciu w przycisk Modal pojawi się okienko z informacjami.
								Menu boczne wyświetli się po kliknięciu w ikonę w prawym górnym
								rogu. Do wyboru mam także 2 opcje wyświetlania wiadomości.
								Przyciski w prawym górnym rogu pozwolą na zmianę widoku
								wiadomości.
							</Description>
						</ListItem>
					</List>
					<Footer />
				</>
			)}
		</>
	);
}
const List = styled.ul`
	list-style: none;
	margin-top: 7rem;
	padding: 0;
`;

const ListItem = styled.li`
	position: relative;
	counter-increment: list;
	max-width: 45rem;
	margin: 1rem auto;
	padding: 1rem 1rem 1rem;
	box-shadow: 0.1rem 0.1rem 1.5rem rgba(0, 0, 0, 0.3);
	border-radius: 0.25rem;
	overflow: hidden;
	background-color: white;

	&:before {
		position: absolute;
		top: 1;
		left: 2;
		width: 2rem;
		height: 2rem;
		line-height: 2rem;
		text-align: center;
		font-size: 1.5rem;
		font-weight: bold;
		color: white;
		background-color: #023e8a;
		border-radius: 50%;
	}

	&:hover {
		cursor: pointer;
		box-shadow: 0.1rem 0.1rem 1.5rem rgba(0, 0, 0, 0.5);
	}
`;

const Title = styled.h2`
	display: flex;
	align-items: baseline;
	margin: 0 0 1rem;
	color: rgb(70 70 70);

	&:before {
		display: flex;
		justify-content: center;
		align-items: center;
		flex: 0 0 auto;
		margin-right: 1rem;
		width: 3rem;
		height: 3rem;

		padding: 1rem;
		border-radius: 50%;
		background-color: var(--c1);
		color: white;
	}
`;

const Description = styled.p`
	p {
		margin: 0;
		line-height: 1.6;
	}
`;
const Meta = styled.div`
	display: flex;
	align-items: center;
	font-size: 0.8rem;
	color: gray;
	margin-bottom: 0.5rem; ;
`;
