import ArticleList from "@/components/Content/ArticleList";
import ArticleTiles from "@/components/Content/ArticleTiles";
import Footer from "@/components/UI/Footer";
import ModalRender from "@/components/Modal/ModalRender";
import Navbar from "@/components/UI/Navbar";
import Loading from "@/components/UI/Loading";
import { fetchNews } from "@/store/newsSlice";
import { uiActions } from "@/store/uiSlice";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import styled from "styled-components";
import i18n from "../config/i18n";
import Error from "@/components/UI/Error";

const Country = () => {
	const dispatch = useDispatch();
	const showModalHandler = () => {
		dispatch(uiActions.showModal());
	};

	const [show, setShow] = useState(true);
	const error = useSelector((state) => state.news.error);
	const articles = useSelector((state) => state.news.articles);
	const currentCountry = useSelector((state) => state.news.currentCountry);
	const view = useSelector((state) => state.view.view);
	const lang = useSelector((state) => state.view.lang);
	useEffect(() => {
		const timer = setTimeout(() => {
			setShow(false);
		}, 1000);

		return () => clearTimeout(timer);
	}, []);

	useEffect(() => {
		dispatch(fetchNews(currentCountry));
	}, [dispatch, currentCountry]);

	useEffect(() => {
		i18n.changeLanguage(lang);
	}, [lang]);

	const status = useSelector((state) => state.view.status);

	return (
		<>
			<Head>
				<title>gnNews</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			{show ? (
				<Loading />
			) : (
				<>
					<Navbar onClick={showModalHandler} />
					<ModalRender onHide={showModalHandler} />
					<ArticleContainer>
						{error ? (
							<Error message={error} />
						) : view === "list" ? (
							<ArticleList articles={articles} />
						) : (
							<ArticleTiles articles={articles} />
						)}
					</ArticleContainer>

					<Footer></Footer>
				</>
			)}
		</>
	);
};

const ArticleContainer = styled.div`
	margin-top: 7rem;
	margin-bottom: 1rem;
`;

export default Country;
